// <auto-generated />
using DeOlho.SeedWork.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeOlho.Search.Politico.Migrations
{
    [DbContext(typeof(DeOlhoDbContext))]
    [Migration("20190903024349_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DeOlho.Search.Politico.Domain.PalavraSubstituta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Palavra");

                    b.Property<string>("Substituta");

                    b.HasKey("Id");

                    b.HasIndex("Palavra")
                        .IsUnique();

                    b.ToTable("PalavraSubstituta");
                });

            modelBuilder.Entity("DeOlho.Search.Politico.Domain.PoliticoMandato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abrangencia");

                    b.Property<int>("Ano");

                    b.Property<string>("Apelido");

                    b.Property<long>("CPF");

                    b.Property<string>("Cargo");

                    b.Property<bool>("Eleito");

                    b.Property<string>("Nome");

                    b.Property<string>("Partido");

                    b.Property<string>("TermoPesquisa");

                    b.HasKey("Id");

                    b.HasIndex("CPF", "Ano")
                        .IsUnique();

                    b.ToTable("PoliticoMandato");
                });
#pragma warning restore 612, 618
        }
    }
}
